Fix java.lang.NoSuchMethodError on non-Folia platforms
Rename loadWithFolia field to isFolia and rewrite tryLoadWithFolia check (now it checks for Folia class instead of running isFoliaSupported method from PluginMeta).